const stations={
"1호선":["소요산","동두천","양주","의정부","회룡","도봉산","도봉","방학","창동","녹천","월계","광운대","석계","신이문","외대앞","회기","청량리","제기동","신설동","동묘앞","동대문","종로5가","종로3가","종각","시청","서울역","남영","용산","노량진","대방","신길","영등포","신도림","구로","가산디지털단지","독산","금천구청","석수","관악","안양","명학","금정","군포","의왕","성균관대","화서","수원","세류","병점","세마","오산대","오산","진위","송탄","서정리","평택","성환","직산","두정","천안","봉명","쌍용","아산","탕정","배방","온양온천","신창"],
"2호선":["시청","을지로입구","을지로3가","을지로4가","동대문역사문화공원","신당","상왕십리","왕십리","한양대","뚝섬","성수","건대입구","구의","강변","잠실나루","잠실","잠실새내","종합운동장","삼성","선릉","역삼","강남","교대","서초","방배","사당","낙성대","서울대입구","봉천","신림","신대방","구로디지털단지","대림","신도림","문래","영등포구청","당산","합정","홍대입구","신촌","이대","아현","충정로"],
"3호선":["대화","주엽","정발산","마두","백석","대곡","화정","원당","원흥","삼송","지축","구파발","연신내","불광","녹번","홍제","무악재","독립문","경복궁","안국","종로3가","을지로3가","충무로","동대입구","약수","금호","옥수","압구정","신사","잠원","고속터미널","교대","남부터미널","양재","매봉","도곡","대치","학여울","대청","일원","수서","가락시장","경찰병원","오금"],
"4호선":["진접","오남","별내별가람","당고개","상계","노원","창동","쌍문","수유","미아","미아사거리","길음","성신여대입구","한성대입구","혜화","동대문","동대문역사문화공원","충무로","명동","회현","서울역","숙대입구","삼각지","신용산","이촌","동작","총신대입구","사당","남태령","선바위","경마공원","대공원","과천","정부과천청사","인덕원","평촌","범계","금정","산본","수리산","대야미","반월","상록수","한대앞","중앙","고잔","초지","안산","신길온천","정왕","오이도"],
"5호선":["방화","개화산","김포공항","송정","마곡","발산","우장산","화곡","까치산","신정","목동","오목교","양평","영등포구청","영등포시장","신길","여의도","여의나루","마포","공덕","애오개","충정로","서대문","광화문","종로3가","을지로4가","동대문역사문화공원","청구","신금호","행당","왕십리","마장","답십리","장한평","군자","아차산","광나루","천호","강동","길동","굽은다리","명일","고덕","상일동","강일","미사","하남풍산","하남시청","하남검단산","둔촌동","올림픽공원","방이","오금","개롱","거여","마천"],
"6호선":["응암","역촌","불광","독바위","연신내","구산","새절","증산","디지털미디어시티","월드컵경기장","마포구청","망원","합정","상수","광흥창","대흥","공덕","효창공원앞","삼각지","녹사평","이태원","한강진","버티고개","약수","청구","신당","동묘앞","창신","보문","안암","고려대","월곡","상월곡","돌곶이","석계","태릉입구","화랑대","봉화산","신내"],
"7호선":["장암","도봉산","수락산","마들","노원","중계","하계","공릉","태릉입구","먹골","중화","상봉","면목","사가정","용마산","중곡","군자","어린이대공원","건대입구","뚝섬유원지","청담","강남구청","학동","논현","반포","고속터미널","내방","이수","남성","숭실대입구","상도","장승배기","신대방삼거리","보라매","신풍","대림","남구로","가산디지털단지","철산","광명사거리","천왕","온수","까치울","부천종합운동장","춘의","신중동","부천시청","상동","삼산체육관","굴포천","부평구청","산곡","석남"],
"8호선":["암사","천호","강동구청","몽촌토성","잠실","석촌","송파","가락시장","문정","장지","복정","남위례","산성","남한산성입구","단대오거리","신흥","수진","모란"],
"9호선":["개화","김포공항","공항시장","신방화","마곡나루","양천향교","가양","증미","등촌","염창","신목동","선유도","당산","국회의사당","여의도","샛강","노량진","노들","흑석","동작","구반포","신반포","고속터미널","사평","신논현","언주","선정릉","삼성중앙","봉은사","종합운동장","삼전","석촌고분","석촌","송파나루","한성백제","올림픽공원","둔촌오륜","중앙보훈병원"]
};
const lineOrder=Object.keys(stations);
const lineColors={"1호선":"#2563eb","2호선":"#16a34a","3호선":"#f97316","4호선":"#38bdf8","5호선":"#7c3aed","6호선":"#a16207","7호선":"#4d7c0f","8호선":"#ec4899","9호선":"#ca8a04"};
const transferGroups={};
for(const line of lineOrder){for(const station of stations[line]){transferGroups[station]??=[];transferGroups[station].push(line)}}
const hours=[];for(let h=5;h<=23;h++)hours.push(String(h).padStart(2,"0"));
const minutes=["00","15","30","45"];
const times=[];for(const h of hours){for(const m of minutes){if(h==="23"&&Number(m)>30)continue;times.push(`${h}:${m}`)}}
let startLine="1호선",endLine="2호선",startStation="서울역",endStation="강남",selectedHour="08",selectedMinute="00",selectedTime="08:00",crowdData=[];
const $=id=>document.getElementById(id);
const startLineSelect=$("startLineSelect"),endLineSelect=$("endLineSelect"),startSelect=$("startSelect"),endSelect=$("endSelect"),hourButtons=$("hourButtons"),minuteButtons=$("minuteButtons"),selectedTimeText=$("selectedTimeText"),withinHourTip=$("withinHourTip"),chart=$("chart"),selectedPercent=$("selectedPercent"),statusBadge=$("statusBadge"),resultText=$("resultText"),recommendTime=$("recommendTime"),dataSource=$("dataSource"),editor=$("editor"),inputRows=$("inputRows"),stopCount=$("stopCount"),travelTime=$("travelTime"),transferText=$("transferText"),routePath=$("routePath"),morningBtn=$("morningBtn"),eveningBtn=$("eveningBtn"),themeToggle=$("themeToggle"),toastBar=$("toastBar");
function initTheme(){const saved=localStorage.getItem("theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");applyTheme(saved)}
function applyTheme(t){document.documentElement.setAttribute("data-theme",t);localStorage.setItem("theme",t);themeToggle.textContent=t==="dark"?"☀️":"🌙"}
themeToggle.onclick=()=>applyTheme(document.documentElement.getAttribute("data-theme")==="dark"?"light":"dark");
let toastTimer;function showToast(msg,isError=false){clearTimeout(toastTimer);toastBar.textContent=msg;toastBar.className="toast"+(isError?" error":"");toastTimer=setTimeout(()=>toastBar.classList.add("hidden"),4500)}
function stationWeight(name){const busy=["서울역","시청","종로3가","동대문역사문화공원","왕십리","건대입구","잠실","고속터미널","강남","교대","사당","신도림","대림","홍대입구","합정","여의도","공덕","김포공항","노량진","가산디지털단지","선릉","삼성","종합운동장","천호","오금","노원","창동"];return busy.includes(name)?17:name.length<=2?8:4}
function pathBetween(line,a,b){const list=stations[line],s=list.indexOf(a),e=list.indexOf(b);if(s<0||e<0)return[];const step=s<=e?1:-1,path=[];for(let i=s;;i+=step){path.push({line,station:list[i],transfer:false});if(i===e)break}return path}
function neighbors(node){const [line,idxText]=node.split("|");const idx=Number(idxText),list=stations[line],out=[];if(idx>0)out.push({node:`${line}|${idx-1}`,cost:1,type:"move"});if(idx<list.length-1)out.push({node:`${line}|${idx+1}`,cost:1,type:"move"});const station=list[idx];for(const other of transferGroups[station]||[]){if(other!==line){const otherIdx=stations[other].indexOf(station);out.push({node:`${other}|${otherIdx}`,cost:3,type:"transfer"})}}return out}
function findRoute(){const start=`${startLine}|${stations[startLine].indexOf(startStation)}`,target=`${endLine}|${stations[endLine].indexOf(endStation)}`;const q=[start],dist={[start]:0},prev={};let head=0;while(head<q.length){const cur=q[head++];if(cur===target)break;for(const edge of neighbors(cur)){const nd=dist[cur]+edge.cost;if(dist[edge.node]===undefined||nd<dist[edge.node]){dist[edge.node]=nd;prev[edge.node]={node:cur,type:edge.type};q.push(edge.node)}}}let nodes=[];if(dist[target]===undefined)return pathBetween(startLine,startStation,endStation);for(let cur=target;cur;cur=prev[cur]?.node)nodes.push(cur);nodes.reverse();const path=[];let transfers=0;for(let i=0;i<nodes.length;i++){const [line,idxText]=nodes[i].split("|");const station=stations[line][Number(idxText)];const next=nodes[i+1];const isTransfer=next&&next.split("|")[1]===idxText&&stations[next.split("|")[0]][Number(next.split("|")[1])]===station&&next.split("|")[0]!==line; if(i>0){const last=path[path.length-1];if(last&&last.station===station&&last.line!==line){last.transfer=true;last.toLine=line;transfers++;continue}}path.push({line,station,transfer:!!isTransfer,toLine:isTransfer?next.split("|")[0]:null})}return{path,transfers}}
function routeInfo(){if(startLine===endLine){const path=pathBetween(startLine,startStation,endStation);const stops=Math.max(0,path.length-1);return{path,stops,transfers:0,time:stops*2+3,transferStations:[]}}const found=findRoute();const path=found.path||found;const transfers=found.transfers||path.filter(p=>p.transfer).length;const stops=Math.max(0,path.filter((p,i)=>i===0||p.station!==path[i-1].station).length-1);const transferStations=path.filter(p=>p.transfer).map(p=>p.station);const time=stops*2+3+transfers*6;return{path,stops,transfers,time,transferStations}}
function makeCrowdData(){const route=routeInfo();const avgWeight=route.path.reduce((sum,item)=>sum+stationWeight(item.station),0)/Math.max(1,route.path.length);const base=25+route.transfers*4+Number(startLine[0])%3;return times.map(time=>{const [h,m]=time.split(":").map(Number),hour=h+m/60;const morning=47*Math.exp(-Math.pow(hour-8.25,2)/1.15),evening=42*Math.exp(-Math.pow(hour-18.35,2)/1.5),lunch=10*Math.exp(-Math.pow(hour-12.7,2)/4.5),distance=Math.min(15,route.stops*.42),transferBoost=route.transfers?5*route.transfers:0,wave=4*Math.sin((hour+route.path.length+Number(startLine[0]))*1.5);const value=Math.round(Math.max(8,Math.min(99,base+avgWeight+morning+evening+lunch+distance+transferBoost+wave)));return{time,crowd:value}})}
function getLevel(crowd){if(crowd<45)return{text:"여유",color:"var(--green)"};if(crowd<70)return{text:"보통",color:"var(--yellow)"};if(crowd<85)return{text:"혼잡",color:"var(--orange)"};return{text:"매우 혼잡",color:"var(--red)"}}
function getBestTime(){return[...crowdData].sort((a,b)=>a.crowd-b.crowd)[0]}
function getBestInSelectedHour(){const list=crowdData.filter(item=>item.time.startsWith(selectedHour+":"));return[...list].sort((a,b)=>a.crowd-b.crowd)[0]}
function fillLineSelect(select,value){select.innerHTML="";lineOrder.forEach(line=>{const o=document.createElement("option");o.value=line;o.textContent=line;select.appendChild(o)});select.value=value}
function fillSelect(select,line,value){select.innerHTML="";stations[line].forEach(station=>{const o=document.createElement("option");o.value=station;o.textContent=station;select.appendChild(o)});select.value=value}
function validateStations(){if(!stations[startLine].includes(startStation))startStation=stations[startLine][0];if(!stations[endLine].includes(endStation))endStation=stations[endLine][Math.min(5,stations[endLine].length-1)];if(startLine===endLine&&startStation===endStation){const list=stations[startLine],i=list.indexOf(startStation);endStation=list[Math.min(i+1,list.length-1)]||list[Math.max(i-1,0)]}}
function setSelectedTime(h,m){selectedHour=h;selectedMinute=m;selectedTime=`${h}:${m}`;selectedTimeText.textContent=selectedTime}
function renderRoute(){const route=routeInfo();stopCount.textContent=`${route.stops}개`;travelTime.textContent=`약 ${route.time}분`;transferText.textContent=route.transfers?`${route.transferStations.join(", ")}역 환승 ${route.transfers}회`:"환승 없음";routePath.innerHTML="";route.path.forEach((item,idx)=>{const chip=document.createElement("div");chip.className="station-chip"+(item.transfer?" transfer":"");chip.textContent=item.transfer?`${item.station} 환승 → ${item.toLine}`:`${item.line} ${item.station}`;chip.style.borderColor=item.transfer?"var(--transfer-border)":lineColors[item.line];routePath.appendChild(chip);if(idx<route.path.length-1){const arrow=document.createElement("div");arrow.className="arrow";arrow.textContent="→";routePath.appendChild(arrow)}})}
function renderHourButtons(){hourButtons.innerHTML="";hours.forEach(h=>{const btn=document.createElement("button");btn.className="hour-btn"+(h===selectedHour?" active":"");btn.textContent=`${Number(h)}시`;btn.onclick=()=>{setSelectedTime(h,minutes.includes(selectedMinute)?selectedMinute:"00");render()};hourButtons.appendChild(btn)})}
function renderMinuteButtons(){minuteButtons.innerHTML="";times.filter(t=>t.startsWith(selectedHour+":")).map(t=>t.split(":")[1]).forEach(m=>{const btn=document.createElement("button");btn.className="minute-btn"+(m===selectedMinute?" active":"");btn.textContent=`${m}분`;btn.onclick=()=>{setSelectedTime(selectedHour,m);render()};minuteButtons.appendChild(btn)})}
function renderChart(){const bestHour=getBestInSelectedHour();chart.innerHTML="";crowdData.forEach(item=>{const level=getLevel(item.crowd),wrap=document.createElement("div");wrap.className="bar-wrap";const barBox=document.createElement("div");barBox.className="bar-box";const bar=document.createElement("div");bar.className="bar"+(item.time===selectedTime?" selected":"")+(bestHour&&item.time===bestHour.time?" best-in-hour":"");bar.style.height=`${item.crowd}%`;bar.style.background=level.color;bar.innerHTML=`<strong>${item.crowd}%</strong>`;barBox.appendChild(bar);const label=document.createElement("div");label.className="time-label";label.textContent=item.time;wrap.appendChild(barBox);wrap.appendChild(label);chart.appendChild(wrap)})}
function renderResult(){const current=crowdData.find(item=>item.time===selectedTime)||crowdData[0],level=getLevel(current.crowd),best=getBestTime(),bestHour=getBestInSelectedHour(),route=routeInfo();selectedPercent.textContent=current.crowd;statusBadge.textContent=level.text;statusBadge.style.background=level.color;statusBadge.style.color=current.crowd<70?"var(--text)":"white";recommendTime.textContent=best.time;selectedTimeText.textContent=selectedTime;if(bestHour)withinHourTip.innerHTML=`${Number(selectedHour)}시대 추천: <strong>${bestHour.time}</strong> · 혼잡도 ${bestHour.crowd}%`;const transferPhrase=route.transfers?`, ${route.transferStations.join(", ")}역에서 환승`:"";const baseText=`${startLine} ${startStation} → ${endLine} ${endStation}${transferPhrase}, ${selectedTime} 출발은`;if(current.crowd>=85)resultText.textContent=`${baseText} 매우 혼잡합니다. ${best.time} 출발이 가장 여유롭고, 예상 소요 시간은 약 ${route.time}분입니다.`;else if(current.crowd>=70)resultText.textContent=`${baseText} 혼잡한 편입니다. 가능하다면 ${best.time} 출발을 추천합니다.`;else resultText.textContent=`${baseText} 비교적 이용하기 괜찮은 시간대입니다. 예상 소요 시간은 약 ${route.time}분입니다.`}
function renderInputs(){inputRows.innerHTML="";crowdData.forEach(item=>{const box=document.createElement("div");box.className="input-box";box.innerHTML=`<label>${item.time}</label><input type="number" min="0" max="100" value="${item.crowd}" data-time="${item.time}"/>`;inputRows.appendChild(box)})}
function refreshData(sourceText="데이터 출처: 1~9호선 체험용 예시 데이터"){validateStations();crowdData=makeCrowdData();dataSource.textContent=sourceText;render()}
function render(){fillLineSelect(startLineSelect,startLine);fillLineSelect(endLineSelect,endLine);fillSelect(startSelect,startLine,startStation);fillSelect(endSelect,endLine,endStation);renderRoute();renderHourButtons();renderMinuteButtons();renderChart();renderResult();renderInputs()}
function clearQuick(){morningBtn.classList.remove("active");eveningBtn.classList.remove("active")}
startLineSelect.onchange=()=>{startLine=startLineSelect.value;validateStations();setSelectedTime("08","00");clearQuick();refreshData()};
endLineSelect.onchange=()=>{endLine=endLineSelect.value;validateStations();setSelectedTime("08","00");clearQuick();refreshData()};
startSelect.onchange=()=>{startStation=startSelect.value;validateStations();refreshData()};
endSelect.onchange=()=>{endStation=endSelect.value;validateStations();refreshData()};
morningBtn.onclick=()=>{clearQuick();morningBtn.classList.add("active");setSelectedTime("08","00");render()};
eveningBtn.onclick=()=>{clearQuick();eveningBtn.classList.add("active");setSelectedTime("18","00");render()};
$("editBtn").onclick=()=>editor.classList.toggle("hidden");
$("applyBtn").onclick=()=>{const inputs=inputRows.querySelectorAll("input");crowdData=[...inputs].map(input=>({time:input.dataset.time,crowd:Math.max(0,Math.min(100,Number(input.value)||0))}));dataSource.textContent=`데이터 출처: 사용자 직접 입력 · ${startLine} ${startStation} → ${endLine} ${endStation}`;render()};
$("loadApiBtn").onclick=async()=>{dataSource.textContent="데이터 출처: API 호출 시도 중...";try{const response=await fetch("https://example.com/subway-route-crowd-api");if(!response.ok)throw new Error("API 응답 실패");const apiData=await response.json();crowdData=apiData.map(item=>({time:item.time,crowd:item.crowd}));dataSource.textContent=`데이터 출처: 공공데이터 API · ${startLine} ${startStation} → ${endLine} ${endStation}`;showToast("공공데이터 API에서 혼잡도를 불러왔습니다.")}catch(error){crowdData=makeCrowdData();dataSource.textContent=`데이터 출처: 체험용 가상 공공데이터 · ${startLine} ${startStation} → ${endLine} ${endStation}`;showToast("체험용 가상 공공데이터를 기반으로 조회합니다.",true)}setSelectedTime("08","00");render()};
initTheme();refreshData();
